### ISSUE TITLE
Hackernoon code example images not shown

### ISSUE THREAD

**Issue by bartduisters** [ImreC/feathers-verification-emails#2]
Instead, this image is shown: https://avatars2.githubusercontent.com/u/9742684?s=400&v=4

The article: https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2

**Comment by ImreC** [comment]
Hi Bart,

This is due to the new Hacker Noon platform not yet being ready to properly
display articles. I am very bummed out that they already migrated
everything. You can view the actual article here:
https://medium.com/hackernoon/setting-up-email-verification-in-feathersjs-ce764907e4f2.
Cheers!

**Comment by bartduisters** [comment]
Thanks for the link. I'll close the issue!
